name: Publish Image
on:
  push: # push 到主分支主动 发布
    branches: ["release"]
    paths-ignore: # 忽略一些不必要的文件
      - ".gitignore"
      - "README.md"
      - ".vscode/**"

env:
  REGISTRY_IMAGE: s-admin
  GITHUB_NAME: zhihao2030

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        node_version: [ 16.16.0 ]
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
          cache: 'npm'

      - name: Install Dependencies
        run: |
          npm ci
      - name: Build
        run: npm run build
      - name: Show Dir
        run: ls
      - name: Build the  Docker image
        run:
          | # 运用 上一步写的 Dockerfile 构建镜像并发布到私有库房； 发布完结能够去 https://github.com/MrGaoGang?tab=packages 检查
          docker build . --file Dockerfile --tag ghcr.io/${{ env.GITHUB_NAME }}/${{ env.REGISTRY_IMAGE }}:latest
          docker push ghcr.io/${{ env.GITHUB_NAME }}/${{ env.REGISTRY_IMAGE }}:latest
